"""primeira vercao alb

Revision ID: a63fcf9136e5
Revises: 
Create Date: 2025-11-07 20:05:26.365814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a63fcf9136e5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'LigaçãoPokemonHabilidades', 'Habilidades', ['id_habilidade'], ['id'])
    op.create_foreign_key(None, 'LigaçãoPokemonHabilidades', 'Pokemons', ['id_pokemon'], ['id'])
    op.alter_column('Pokemons', 'Geracao',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Pokemons', 'Geracao',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'LigaçãoPokemonHabilidades', type_='foreignkey')
    op.drop_constraint(None, 'LigaçãoPokemonHabilidades', type_='foreignkey')
    # ### end Alembic commands ###
